use std::env;
use std::fs;
use std::path::Path;

// 「粉丝福利」礼物 key 的滚动 XOR 混淆垫片。
// 注意: 客户端混淆只能延缓提取、不能真正保护密钥 —— 真正的止损是给该 key 设额度封顶。
const GIFT_PAD: [u8; 8] = [0x9E, 0x37, 0x79, 0xB1, 0x5A, 0xC4, 0x2D, 0xE6];

// Kimi For Coding「免费额度赠送」token —— 源码内置, 开箱即用。
// 任何构建(含本地 dev)都会把它种进供应商坞的 kimi-for-coding, 无需配置 CI secret。
// 设了环境变量 POLARIS_GIFT_KIMI_KEY 时以环境变量为准(便于日后轮换 / 失效替换)。
// 提醒: 这是公开赠送的共享 token, 明文进 git 与随二进制分发同等暴露面, 可接受。
const GIFT_KIMI_DEFAULT: &str =
    "sk-kimi-9WLHZfUxcpzi2l9AsTqMatBYOzpHoCtOsxIVFuyRIlQIPDz76p0aoXLjSHuVw4pu";

/// 把明文 key 按滚动 XOR 编成 `0xAB, 0xCD, …` 字节字面量(供生成的 Rust const 用)。
fn obfuscate(key: &str) -> String {
    key.as_bytes()
        .iter()
        .enumerate()
        .map(|(i, b)| format!("0x{:02X}", b ^ GIFT_PAD[i % GIFT_PAD.len()]))
        .collect::<Vec<_>>()
        .join(", ")
}

fn main() {
    // tauri_build 仅在桌面构建时调用; server (Docker) 构建无需 Tauri 上下文/资源清单,
    // 跳过它即可在无 webkit2gtk 的 Linux 镜像里编译同一份源码。
    #[cfg(feature = "desktop")]
    tauri_build::build();

    // 构建期从环境变量注入礼物 key(CI 走 GitHub secret POLARIS_GIFT_MINIMAX_KEY)。
    // 本地 dev 构建未设此变量时, 注入空串 → 运行时不种子, 不影响开发。
    println!("cargo:rerun-if-env-changed=POLARIS_GIFT_MINIMAX_KEY");
    println!("cargo:rerun-if-env-changed=POLARIS_GIFT_KIMI_KEY");
    let minimax_key = env::var("POLARIS_GIFT_MINIMAX_KEY").unwrap_or_default();
    // Kimi: 环境变量优先, 否则回落源码内置默认 → 始终开箱即用。
    let kimi_key = env::var("POLARIS_GIFT_KIMI_KEY")
        .ok()
        .filter(|s| !s.trim().is_empty())
        .unwrap_or_else(|| GIFT_KIMI_DEFAULT.to_string());

    let pad: Vec<String> = GIFT_PAD.iter().map(|b| format!("0x{:02X}", b)).collect();
    let pad = pad.join(", ");

    let body = format!(
        "// AUTO-GENERATED by build.rs — 构建期注入, 勿手改。\n\
         pub(crate) const GIFT_MINIMAX_OBF: &[u8] = &[{mm}];\n\
         pub(crate) const GIFT_MINIMAX_PAD: &[u8] = &[{pad}];\n\
         pub(crate) const GIFT_KIMI_OBF: &[u8] = &[{kimi}];\n\
         pub(crate) const GIFT_KIMI_PAD: &[u8] = &[{pad}];\n",
        mm = obfuscate(&minimax_key),
        kimi = obfuscate(&kimi_key),
        pad = pad,
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    fs::write(Path::new(&out_dir).join("gift_key.rs"), body).expect("write gift_key.rs failed");
}
