//! 百人专家团花名册 — 100 张能力卡（编译期内嵌）
//!
//! 来源: VoltAgent/wshobson/awesome-claude-code-subagents (MIT) + 补强自研

use crate::expert::ExpertCard;

/// 构建单个专家卡片
fn ec(
    id: &'static str,
    name: &'static str,
    icon: &'static str,
    role: &'static str,
    description: &'static str,
    trigger_signals: &[&'static str],
    complements: &'static str,
    keywords: &[&'static str],
    capabilities: &[&'static str],
    claude_md_ref: &'static str,
    model_hint: &'static str,
    cost_tier: u8,
    exclusive_with: &[&'static str],
    source: &'static str,
    license: &'static str,
    group: &'static str,
) -> ExpertCard {
    ExpertCard {
        id: id.to_string(),
        name: name.to_string(),
        icon: icon.to_string(),
        role: role.to_string(),
        description: description.to_string(),
        trigger_signals: trigger_signals.iter().map(|s| s.to_string()).collect(),
        complements: complements.to_string(),
        keywords: keywords.iter().map(|s| s.to_string()).collect(),
        capabilities: capabilities.iter().map(|s| s.to_string()).collect(),
        claude_md_ref: claude_md_ref.to_string(),
        model_hint: model_hint.to_string(),
        cost_tier,
        exclusive_with: exclusive_with.iter().map(|s| s.to_string()).collect(),
        source: source.to_string(),
        license: license.to_string(),
        group: group.to_string(),
    }
}

/// 运行时构建所有专家列表（避免 const 限制）
pub fn build_experts() -> Vec<ExpertCard> {
    vec![
        // ── 编排/统帅 (5) ──
        ec("chief-strategist", "首席战略师", "🧭", "拆解·组队·收口（lead）",
           "任何多步骤、需拆解组队的任务默认入场当编排器",
           &["多步骤", "拆解", "组队", "战略", "规划", "目标"],
           "交付/战略",
           &["planning", "strategy", "orchestration"],
           &["read_code", "run_bash"],
           "experts/orchestration/chief-strategist.md", "sonnet", 3, &[],
           "ChatDev/MetaGPT", "MIT", "orchestration"),
        ec("multi-agent-coordinator", "多Agent协调员", "🔄", "并行调度·依赖管理·交接",
           "子任务≥2 且可独立并行时管调度",
           &["并行", "调度", "多任务", "协作", "Agent"],
           "并行/协调",
           &["parallel", "coordination", "task-scheduling"],
           &["read_code", "run_bash"],
           "experts/orchestration/multi-agent-coordinator.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "orchestration"),
        ec("knowledge-synthesizer", "知识综合器", "🧩", "跨分支归并·去重·收口",
           "多个并行分支产出需合成一份时",
           &["综合", "归并", "去重", "总结", "汇总"],
           "综合/收口",
           &["synthesis", "merge", "dedup"],
           &["read_code", "run_bash"],
           "experts/orchestration/knowledge-synthesizer.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "orchestration"),
        ec("strategy-planner", "OKR/战略规划", "🎯", "目标拆里程碑·北极星指标",
           "目标模糊、需先拆成可执行计划时",
           &["OKR", "战略", "规划", "目标", "里程碑", "KPI"],
           "战略/规划",
           &["okr", "strategy", "planning", "metrics"],
           &["read_code", "run_bash"],
           "experts/orchestration/strategy-planner.md", "sonnet", 3, &[],
           "补强", "北极星综合", "orchestration"),
        ec("context-manager", "上下文管理器", "📋", "长上下文·记忆地图维护",
           "长任务多轮、上下文将溢出时",
           &["长上下文", "记忆", "溢出", "上下文", "多轮"],
           "上下文",
           &["context", "memory", "long-context"],
           &["read_code", "run_bash"],
           "experts/orchestration/context-manager.md", "sonnet", 2, &[],
           "wshobson", "MIT", "orchestration"),

        // ── 系统架构 (10) ──
        ec("backend-architect", "后端架构师", "🏛", "API 边界·服务拆分·DB schema",
           "要定接口边界/服务划分/数据建模时",
           &["后端", "API", "服务", "数据库", "架构"],
           "后端/架构",
           &["api", "backend", "database", "architecture"],
           &["read_code", "run_bash"],
           "experts/system/backend-architect.md", "sonnet", 2, &[],
           "wshobson", "MIT", "system_arch"),
        ec("frontend-architect", "前端架构师", "🎨", "组件体系·状态·性能预算",
           "前端结构/状态管理/性能待定时",
           &["前端", "组件", "状态", "性能", "架构"],
           "前端/架构",
           &["frontend", "react", "vue", "component", "state"],
           &["read_code", "run_bash"],
           "experts/system/frontend-architect.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "system_arch"),
        ec("architecture-advisor", "系统架构权衡", "⚖️", "ADR·多方案 trade-off",
           "多方案取舍、需写决策记录时",
           &["架构", "权衡", "trade-off", "ADR", "决策"],
           "架构/决策",
           &["architecture", "tradeoff", "adr"],
           &["read_code", "run_bash"],
           "experts/system/architecture-advisor.md", "sonnet", 3, &[],
           "补强", "北极星综合", "system_arch"),
        ec("api-contract-designer", "API契约设计", "📡", "OpenAPI/gRPC·版本兼容·契约测试",
           "定接口契约、跨端/跨服务对齐时",
           &["API", "契约", "OpenAPI", "gRPC", "接口"],
           "契约/接口",
           &["openapi", "grpc", "api-contract"],
           &["read_code", "run_bash"],
           "experts/system/api-contract-designer.md", "sonnet", 2, &[],
           "补强", "北极星综合", "system_arch"),
        ec("cloud-architect", "云架构师", "☁️", "AWS/Azure/GCP·成本优化",
           "上云选型、跨云、云成本时",
           &["云", "AWS", "Azure", "GCP", "上云"],
           "云/架构",
           &["aws", "azure", "gcp", "cloud"],
           &["read_code", "run_bash"],
           "experts/system/cloud-architect.md", "sonnet", 3, &[],
           "wshobson", "MIT", "system_arch"),
        ec("kubernetes-architect", "云原生/K8s架构师", "☸️", "云原生·GitOps·编排",
           "容器编排/GitOps/集群时",
           &["K8s", "Kubernetes", "Docker", "云原生", "GitOps"],
           "容器/编排",
           &["kubernetes", "docker", "gitops", "cloud-native"],
           &["read_code", "run_bash"],
           "experts/system/kubernetes-architect.md", "sonnet", 2, &[],
           "wshobson", "MIT", "system_arch"),
        ec("microservices-architect", "微服务架构师", "🔀", "拆分·契约·容错",
           "单体拆微服务、服务治理时",
           &["微服务", "拆分", "服务治理", "容错"],
           "微服务",
           &["microservices", "service-mesh", "fault-tolerance"],
           &["read_code", "run_bash"],
           "experts/system/microservices-architect.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "system_arch"),
        ec("graphql-architect", "GraphQL架构师", "◈", "schema·解析器·联邦",
           "用 GraphQL/联邦图时",
           &["GraphQL", "schema", "联邦"],
           "GraphQL",
           &["graphql", "federation", "schema"],
           &["read_code", "run_bash"],
           "experts/system/graphql-architect.md", "sonnet", 2, &[],
           "wshobson", "MIT", "system_arch"),
        ec("event-sourcing-architect", "事件溯源架构师", "🔄", "CQRS·saga·审计追溯",
           "需事件溯源/审计/最终一致时",
           &["事件溯源", "CQRS", "saga", "审计"],
           "事件溯源",
           &["event-sourcing", "cqrs", "saga", "audit"],
           &["read_code", "run_bash"],
           "experts/system/event-sourcing-architect.md", "sonnet", 3, &[],
           "wshobson", "MIT", "system_arch"),
        ec("platform-engineer-arch", "平台工程师", "🧱", "内部平台·golden path",
           "建内部平台/标准化时",
           &["平台", "内部平台", "DevEx", "golden path"],
           "平台/效率",
           &["platform", "devex", "golden-path"],
           &["read_code", "run_bash"],
           "experts/system/platform-engineer.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "system_arch"),

        // ── 语言专精 (12) ──
        ec("python-pro", "Python专家", "🐍", "Pythonic·异步·类型",
           "用 Python 实现/异步/性能时",
           &["Python", "python", "异步", "类型"],
           "Python",
           &["python", "async", "typing"],
           &["read_code", "run_bash"],
           "experts/language/python-pro.md", "sonnet", 2, &[],
           "wshobson", "MIT", "language"),
        ec("typescript-pro", "TypeScript/Node专家", "📘", "类型体操·Node 运行时",
           "TS 类型/Node 服务时",
           &["TypeScript", "TS", "Node", "nodejs"],
           "TypeScript",
           &["typescript", "node", "nodejs"],
           &["read_code", "run_bash"],
           "experts/language/typescript-pro.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "language"),
        ec("golang-pro", "Go专家", "🔷", "并发·高性能·简洁",
           "Go 并发/高吞吐服务时",
           &["Go", "golang", "并发", "高性能"],
           "Go",
           &["golang", "go", "concurrency"],
           &["read_code", "run_bash"],
           "experts/language/golang-pro.md", "sonnet", 2, &[],
           "wshobson", "MIT", "language"),
        ec("rust-pro", "Rust专家", "🦀", "所有权·系统级·零成本",
           "Rust/系统级/native 时",
           &["Rust", "rust", "系统级", "native"],
           "Rust",
           &["rust", "systems", "native"],
           &["read_code", "run_bash"],
           "experts/language/rust-pro.md", "sonnet", 2, &[],
           "wshobson", "MIT", "language"),
        ec("java-pro", "Java专家", "☕", "JVM·Spring 生态",
           "JVM/Spring 后端时",
           &["Java", "JVM", "Spring"],
           "Java",
           &["java", "jvm", "spring"],
           &["read_code", "run_bash"],
           "experts/language/java-pro.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "language"),
        ec("cpp-pro", "C/C++专家", "⚙️", "系统级·内存·模板",
           "native/内存敏感/高性能时",
           &["C++", "cpp", "内存", "系统级"],
           "C++",
           &["cpp", "c++", "memory", "systems"],
           &["read_code", "run_bash"],
           "experts/language/cpp-pro.md", "sonnet", 3, &[],
           "wshobson", "MIT", "language"),
        ec("csharp-pro", "C#专家", "🔷", ".NET·Unity·LINQ",
           ".NET/Unity 时",
           &["C#", "csharp", ".NET", "Unity"],
           "C#",
           &["csharp", "dotnet", "unity"],
           &["read_code", "run_bash"],
           "experts/language/csharp-pro.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "language"),
        ec("sql-pro", "SQL专家", "🗄️", "复杂查询·窗口函数·调优",
           "写复杂 SQL/查询调优时",
           &["SQL", "查询", "数据库", "调优"],
           "SQL",
           &["sql", "query", "database", "tuning"],
           &["read_code", "run_bash"],
           "experts/language/sql-pro.md", "sonnet", 2, &[],
           "wshobson", "MIT", "language"),
        ec("ios-developer", "Swift/iOS专家", "🍎", "SwiftUI·原生体验",
           "iOS 原生 App 时",
           &["iOS", "Swift", "SwiftUI", "Apple"],
           "iOS",
           &["ios", "swift", "swiftui", "apple"],
           &["read_code", "run_bash"],
           "experts/language/ios-developer.md", "sonnet", 2, &[],
           "wshobson", "MIT", "language"),
        ec("kotlin-specialist", "Kotlin/Android专家", "🤖", "协程·Jetpack",
           "Android 原生时",
           &["Kotlin", "Android", "Jetpack"],
           "Kotlin",
           &["kotlin", "android", "jetpack"],
           &["read_code", "run_bash"],
           "experts/language/kotlin-specialist.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "language"),
        ec("blockchain-developer", "Solidity/区块链", "⛓️", "智能合约·Web3·链上审计",
           "智能合约/Web3/链上时",
           &["Solidity", "区块链", "Web3", "智能合约"],
           "Web3",
           &["solidity", "blockchain", "web3", "smart-contract"],
           &["read_code", "run_bash"],
           "experts/language/blockchain-developer.md", "sonnet", 3, &[],
           "VoltAgent", "MIT", "language"),
        ec("embedded-systems", "嵌入式/IoT", "📟", "固件·实时·低功耗",
           "固件/实时/硬件交互时",
           &["嵌入式", "IoT", "固件", "ARM", "RTOS"],
           "嵌入式",
           &["embedded", "iot", "firmware", "rtos"],
           &["read_code", "run_bash"],
           "experts/language/embedded-systems.md", "sonnet", 3, &[],
           "VoltAgent", "MIT", "language"),

        // ── 前端/移动 (6) ──
        ec("react-specialist", "React专家", "⚛️", "hooks·渲染优化",
           "React 组件/性能时",
           &["React", "hooks", "前端"],
           "React",
           &["react", "hooks", "frontend"],
           &["read_code", "run_bash"],
           "experts/frontend/react-specialist.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "frontend"),
        ec("vue-expert", "Vue专家", "💚", "组合式 API·生态",
           "Vue 时（Polaris 前端栈）",
           &["Vue", "前端", "组合式API"],
           "Vue",
           &["vue", "frontend"],
           &["read_code", "run_bash"],
           "experts/frontend/vue-expert.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "frontend"),
        ec("nextjs-developer", "Next.js专家", "▲", "SSR/RSC·全栈 React",
           "SSR/全栈 React 时",
           &["Next.js", "SSR", "RSC", "全栈"],
           "Next.js",
           &["nextjs", "ssr", "rsc", "fullstack"],
           &["read_code", "run_bash"],
           "experts/frontend/nextjs-developer.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "frontend"),
        ec("flutter-expert", "Flutter专家", "🦋", "跨端·动画",
           "跨端 App/动画时",
           &["Flutter", "跨端", "Dart"],
           "Flutter",
           &["flutter", "cross-platform", "dart"],
           &["read_code", "run_bash"],
           "experts/frontend/flutter-expert.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "frontend"),
        ec("accessibility-tester", "无障碍审计员", "♿", "WCAG·a11y",
           "无障碍合规/可访问性时",
           &["无障碍", "WCAG", "a11y", "可访问性"],
           "无障碍",
           &["wcag", "accessibility", "a11y"],
           &["read_code", "run_bash"],
           "experts/frontend/accessibility-tester.md", "sonnet", 1, &[],
           "VoltAgent", "MIT", "frontend"),
        ec("mobile-developer", "移动端专家", "📱", "跨平台移动·原生体验",
           "iOS/Android 跨平台时",
           &["移动", "iOS", "Android", "跨平台"],
           "移动端",
           &["mobile", "ios", "android", "cross-platform"],
           &["read_code", "run_bash"],
           "experts/frontend/mobile-developer.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "frontend"),

        // ── DevOps/基础设施 (9) ──
        ec("devops-engineer", "DevOps工程师", "🔧", "流水线·自动化",
           "建 CI 流水线/自动化时",
           &["DevOps", "CI", "流水线", "自动化"],
           "DevOps",
           &["devops", "ci", "pipeline", "automation"],
           &["read_code", "run_bash"],
           "experts/devops/devops-engineer.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "devops"),
        ec("deployment-engineer", "CICD部署工程师", "🚀", "容器化·发布编排",
           "上线/发布/灰度时",
           &["部署", "CICD", "发布", "灰度"],
           "部署",
           &["deploy", "cicd", "release", "canary"],
           &["read_code", "run_bash"],
           "experts/devops/deployment-engineer.md", "sonnet", 2, &[],
           "wshobson", "MIT", "devops"),
        ec("terraform-specialist", "Terraform/IaC专家", "🏗️", "基础设施即代码·状态",
           "用 IaC 管基础设施时",
           &["Terraform", "IaC", "基础设施"],
           "IaC",
           &["terraform", "iac", "infrastructure"],
           &["read_code", "run_bash"],
           "experts/devops/terraform-specialist.md", "sonnet", 2, &[],
           "wshobson", "MIT", "devops"),
        ec("docker-expert", "Docker专家", "🐳", "镜像瘦身·多阶段",
           "容器化/镜像优化时",
           &["Docker", "容器", "镜像"],
           "Docker",
           &["docker", "container", "image"],
           &["read_code", "run_bash"],
           "experts/devops/docker-expert.md", "sonnet", 1, &[],
           "VoltAgent", "MIT", "devops"),
        ec("sre-engineer", "SRE/可观测性", "📊", "SLO·告警·事故复盘",
           "可靠性/监控/postmortem 时",
           &["SRE", "可观测性", "SLO", "告警"],
           "SRE",
           &["sre", "observability", "slo", "alerting"],
           &["read_code", "run_bash"],
           "experts/devops/sre-engineer.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "devops"),
        ec("network-engineer", "网络工程师", "🌐", "负载均衡·流量·排障",
           "网络/流量/连通性排障时",
           &["网络", "负载均衡", "DNS", "流量"],
           "网络",
           &["network", "load-balancing", "dns"],
           &["read_code", "run_bash"],
           "experts/devops/network-engineer.md", "sonnet", 2, &[],
           "wshobson", "MIT", "devops"),
        ec("incident-responder", "事故响应官", "🚨", "生产故障·紧急止血",
           "线上故障/P0 紧急时",
           &["故障", "P0", "事故", "紧急"],
           "事故",
           &["incident", "p0", "emergency"],
           &["read_code", "run_bash"],
           "experts/devops/incident-responder.md", "sonnet", 3, &[],
           "wshobson", "MIT", "devops"),
        ec("ops-engineer", "运维工程师", "⚙️", "运维·监控·巡检",
           "日常运维/监控/巡检时",
           &["运维", "监控", "巡检"],
           "运维",
           &["ops", "monitoring"],
           &["read_code", "run_bash"],
           "experts/devops/ops-engineer.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "devops"),
        ec("platform-engineer-devops", "平台工程师", "🧱", "内部平台·golden path",
           "建内部平台/标准化时",
           &["平台", "内部平台", "DevEx"],
           "平台",
           &["platform", "devex"],
           &["read_code", "run_bash"],
           "experts/devops/platform-engineer.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "devops"),

        // ── 数据 (8) ──
        ec("data-scientist", "数据科学家", "🔬", "建模·统计·洞察",
           "建模/统计/数据洞察时",
           &["数据科学", "建模", "统计", "ML"],
           "数据科学",
           &["data-science", "modeling", "statistics", "ml"],
           &["read_code", "run_bash"],
           "experts/data/data-scientist.md", "sonnet", 3, &[],
           "wshobson", "MIT", "data"),
        ec("data-engineer", "数据工程师", "🔄", "ETL·数仓·流式",
           "建数据管道/数仓时",
           &["数据工程", "ETL", "数仓", "流式"],
           "数据工程",
           &["data-engineering", "etl", "data-warehouse"],
           &["read_code", "run_bash"],
           "experts/data/data-engineer.md", "sonnet", 2, &[],
           "wshobson", "MIT", "data"),
        ec("data-analyst", "数据分析师", "📈", "指标·可视化·归因",
           "指标分析/归因/报表时",
           &["数据分析", "指标", "可视化", "归因"],
           "分析",
           &["data-analysis", "metrics", "visualization"],
           &["read_code", "run_bash"],
           "experts/data/data-analyst.md", "sonnet", 1, &[],
           "VoltAgent", "MIT", "data"),
        ec("database-architect", "数据库架构师", "🗄️", "选型·schema 建模",
           "选库/建表/数据建模时",
           &["数据库", "选型", "schema"],
           "数据库",
           &["database", "schema", "modeling"],
           &["read_code", "run_bash"],
           "experts/data/database-architect.md", "sonnet", 2, &[],
           "wshobson", "MIT", "data"),
        ec("database-optimizer", "数据库优化师", "⚡", "慢查询·索引·迁移",
           "慢查询/索引/迁移时",
           &["数据库优化", "慢查询", "索引"],
           "优化",
           &["database", "optimization", "query-tuning"],
           &["read_code", "run_bash"],
           "experts/data/database-optimizer.md", "sonnet", 2, &[],
           "wshobson", "MIT", "data"),
        ec("vector-db-engineer", "向量数据库工程师", "🔮", "embedding 存储·ANN",
           "RAG/向量检索/ANN 时",
           &["向量数据库", "embedding", "RAG", "ANN"],
           "向量检索",
           &["vector-db", "embedding", "rag", "ann"],
           &["read_code", "run_bash"],
           "experts/data/vector-db-engineer.md", "sonnet", 2, &[],
           "wshobson", "MIT", "data"),
        ec("data-contract-engineer", "数据契约/质量", "📋", "schema 演进·血缘·校验",
           "数据质量/契约/血缘时",
           &["数据契约", "数据质量", "血缘", "schema"],
           "数据质量",
           &["data-contract", "data-quality", "lineage"],
           &["read_code", "run_bash"],
           "experts/data/data-contract-engineer.md", "sonnet", 2, &[],
           "补强", "北极星综合", "data"),
        ec("dataviz-storyteller", "数据可视化叙事", "📊", "图表选型·数据故事",
           "把数据讲成图表故事/数据→PPT 时",
           &["数据可视化", "图表", "叙事"],
           "可视化",
           &["dataviz", "chart", "storytelling"],
           &["read_code", "run_bash"],
           "experts/data/dataviz-storyteller.md", "sonnet", 2, &[],
           "补强", "北极星综合", "data"),

        // ── AI/机器学习 (7) ──
        ec("ai-engineer", "AI工程师", "🤖", "prompt 流水线·RAG·agent",
           "做 LLM/RAG/agent 应用时",
           &["AI", "LLM", "RAG", "agent", "prompt"],
           "AI/LLM",
           &["ai", "llm", "rag", "agent", "prompt"],
           &["read_code", "run_bash"],
           "experts/ai/ai-engineer.md", "sonnet", 3, &[],
           "wshobson", "MIT", "ai_ml"),
        ec("ml-engineer", "ML工程师", "🧠", "训练·部署·调优",
           "训练/部署模型时",
           &["ML", "机器学习", "训练", "部署"],
           "ML",
           &["ml", "machine-learning", "training"],
           &["read_code", "run_bash"],
           "experts/ai/ml-engineer.md", "sonnet", 3, &[],
           "wshobson", "MIT", "ai_ml"),
        ec("mlops-engineer", "MLOps工程师", "🔄", "模型流水线·监控",
           "模型上线/监控/版本时",
           &["MLOps", "模型", "监控", "流水线"],
           "MLOps",
           &["mlops", "model-monitoring"],
           &["read_code", "run_bash"],
           "experts/ai/mlops-engineer.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "ai_ml"),
        ec("llm-architect", "LLM架构师", "🧠", "推理服务·上下文工程·成本",
           "LLM 推理服务/上下文/成本时",
           &["LLM架构", "推理", "上下文工程", "成本"],
           "LLM架构",
           &["llm", "inference", "context-engineering"],
           &["read_code", "run_bash"],
           "experts/ai/llm-architect.md", "sonnet", 3, &[],
           "VoltAgent", "MIT", "ai_ml"),
        ec("nlp-engineer", "NLP工程师", "📝", "文本抽取·分类",
           "文本处理/抽取/分类时",
           &["NLP", "文本", "抽取", "分类"],
           "NLP",
           &["nlp", "text-processing", "classification"],
           &["read_code", "run_bash"],
           "experts/ai/nlp-engineer.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "ai_ml"),
        ec("prompt-engineer", "提示词工程师", "💬", "prompt 设计·评测",
           "设计/优化/评测 prompt 时",
           &["prompt", "提示词", "评测"],
           "提示词",
           &["prompt", "prompt-engineering"],
           &["read_code", "run_bash"],
           "experts/ai/prompt-engineer.md", "sonnet", 2, &[],
           "wshobson", "MIT", "ai_ml"),
        ec("rl-engineer", "强化学习工程师", "🎮", "RL·策略优化",
           "强化学习/策略优化时",
           &["强化学习", "RL", "策略"],
           "RL",
           &["reinforcement-learning", "rl", "policy"],
           &["read_code", "run_bash"],
           "experts/ai/rl-engineer.md", "sonnet", 3, &[],
           "VoltAgent", "MIT", "ai_ml"),

        // ── 安全/合规 (7) ──
        ec("security-auditor", "安全审计员", "🔍", "OWASP·漏洞·供应链",
           "涉鉴权/对外接口/漏洞/合规时",
           &["安全", "审计", "OWASP", "漏洞", "渗透"],
           "安全",
           &["security", "audit", "owasp", "vulnerability"],
           &["read_code", "run_bash"],
           "experts/security/security-auditor.md", "sonnet", 3, &[],
           "wshobson", "MIT", "security"),
        ec("penetration-tester", "渗透测试员", "🗡️", "攻击面·利用链",
           "验证攻击面/红队时",
           &["渗透", "红队", "攻击面"],
           "渗透测试",
           &["penetration", "red-team", "attack-surface"],
           &["read_code", "run_bash"],
           "experts/security/penetration-tester.md", "sonnet", 3, &[],
           "VoltAgent", "MIT", "security"),
        ec("threat-modeling-expert", "威胁建模专家", "⚠️", "STRIDE·体系化风险",
           "系统性风险评估/设计评审时",
           &["威胁建模", "STRIDE", "风险"],
           "威胁建模",
           &["threat-modeling", "stride", "risk"],
           &["read_code", "run_bash"],
           "experts/security/threat-modeling-expert.md", "sonnet", 3, &[],
           "wshobson", "MIT", "security"),
        ec("appsec-coder", "应用安全工程师", "🛡️", "XSS/CSP·注入防御",
           "处理用户输入/防注入编码时",
           &["应用安全", "XSS", "注入", "CSP"],
           "应用安全",
           &["appsec", "xss", "injection", "csp"],
           &["read_code", "run_bash"],
           "experts/security/appsec-coder.md", "sonnet", 2, &[],
           "wshobson", "MIT", "security"),
        ec("compliance-privacy", "合规/隐私", "📜", "GDPR·数据出境·AI 合规",
           "处理个人数据/跨境/AI 合规时",
           &["合规", "GDPR", "隐私", "AI合规"],
           "合规",
           &["compliance", "gdpr", "privacy", "ai-compliance"],
           &["read_code", "run_bash"],
           "experts/security/compliance-privacy.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "security"),
        ec("license-counsel", "法务/许可证", "⚖️", "开源 license·合同条款",
           "引第三方/开源 license 审查时",
           &["license", "许可证", "开源", "法务"],
           "法务",
           &["license", "open-source", "legal"],
           &["read_code", "run_bash"],
           "experts/security/license-counsel.md", "sonnet", 2, &[],
           "wshobson", "MIT", "security"),
        ec("privacy-engineer", "密码学/数据隐私", "🔐", "加密·脱敏·密钥",
           "加密/脱敏/密钥管理时",
           &["加密", "脱敏", "密钥", "隐私"],
           "隐私",
           &["encryption", "anonymization", "key-management"],
           &["read_code", "run_bash"],
           "experts/security/privacy-engineer.md", "sonnet", 3, &[],
           "VoltAgent", "MIT", "security"),

        // ── 质量/治理 (7) ──
        ec("code-reviewer", "代码评审员", "👀", "可读性·缺陷·模式",
           "合并前/质量把关时",
           &["代码评审", "review", "代码质量"],
           "评审",
           &["code-review", "review", "quality"],
           &["read_code", "run_bash"],
           "experts/quality/code-reviewer.md", "sonnet", 2, &[],
           "wshobson", "MIT", "quality"),
        ec("test-automator", "测试自动化工程师", "🧪", "E2E·覆盖率·回归",
           "建自动化测试/回归时",
           &["测试", "自动化", "E2E", "回归"],
           "测试",
           &["testing", "e2e", "automation", "regression"],
           &["read_code", "run_bash"],
           "experts/quality/test-automator.md", "sonnet", 2, &[],
           "wshobson", "MIT", "quality"),
        ec("qa-expert", "QA专家", "✅", "测试策略·用例",
           "定测试策略/设计用例时",
           &["QA", "测试策略", "用例"],
           "QA",
           &["qa", "test-strategy", "test-case"],
           &["read_code", "run_bash"],
           "experts/quality/qa-expert.md", "sonnet", 1, &[],
           "VoltAgent", "MIT", "quality"),
        ec("performance-engineer", "性能工程师", "⚡", "剖析·瓶颈·调优",
           "性能瓶颈/卡顿/调优时",
           &["性能", "瓶颈", "优化", "profiling"],
           "性能",
           &["performance", "profiling", "bottleneck"],
           &["read_code", "run_bash"],
           "experts/quality/performance-engineer.md", "sonnet", 3, &[],
           "wshobson", "MIT", "quality"),
        ec("debugger", "调试专家", "🔧", "复现·定位·根因",
           "难复现 bug/根因定位时",
           &["调试", "bug", "复现", "根因"],
           "调试",
           &["debug", "bug", "reproduce"],
           &["read_code", "run_bash"],
           "experts/quality/debugger.md", "sonnet", 2, &[],
           "wshobson", "MIT", "quality"),
        ec("refactoring-specialist", "重构专家", "♻️", "坏味道·解耦",
           "代码腐化/解耦/可维护时",
           &["重构", "坏味道", "解耦"],
           "重构",
           &["refactoring", "clean-code", "decoupling"],
           &["read_code", "run_bash"],
           "experts/quality/refactoring-specialist.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "quality"),
        ec("tech-debt-strategist", "技术债治理", "💳", "识别·量化·排期偿还",
           "技术债盘点/排期偿还时",
           &["技术债", "治理", "偿还"],
           "技术债",
           &["tech-debt", "refactoring"],
           &["read_code", "run_bash"],
           "experts/quality/tech-debt-strategist.md", "sonnet", 2, &[],
           "补强", "北极星综合", "quality"),

        // ── 专项技术 (6) ──
        ec("payment-integration", "支付集成专家", "💳", "网关·对账·订阅",
           "带支付/计费/对账/退款时",
           &["支付", "Stripe", "计费", "对账", "退款", "订阅"],
           "支付",
           &["payment", "stripe", "billing", "subscription"],
           &["read_code", "run_bash"],
           "experts/specialty/payment-integration.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "specialty"),
        ec("game-developer", "游戏开发者", "🎮", "引擎·循环·物理",
           "做游戏/引擎/物理时",
           &["游戏", "引擎", "Unity", "Unreal"],
           "游戏",
           &["game", "unity", "game-engine"],
           &["read_code", "run_bash"],
           "experts/specialty/game-developer.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "specialty"),
        ec("legacy-modernizer", "遗留系统现代化", "🏚️", "渐进迁移·绞杀者",
           "老系统迁移/重写时",
           &["遗留系统", "迁移", "现代化"],
           "遗留",
           &["legacy", "migration", "modernization"],
           &["read_code", "run_bash"],
           "experts/specialty/legacy-modernizer.md", "sonnet", 3, &[],
           "wshobson", "MIT", "specialty"),
        ec("browser-automation", "浏览器自动化", "🌐", "爬取·反检测·RPA",
           "爬取/RPA/网页操控时",
           &["浏览器自动化", "爬虫", "RPA", "CloakBrowser"],
           "浏览器",
           &["browser", "automation", "crawl", "rpa"],
           &["read_code", "run_bash"],
           "experts/specialty/browser-automation.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "specialty"),
        ec("fintech-engineer", "资金/支付系统专家", "💹", "支付·交易·对账·风控·合规",
           "支付/计费/对账/退款/订阅 或 金融/交易/风控系统时（已合并支付集成专家）",
           &["支付", "计费", "对账", "退款", "订阅", "金融科技", "交易", "风控", "合规", "Stripe"],
           "资金/支付",
           &["payment", "stripe", "billing", "subscription", "fintech", "trading", "risk-management"],
           &["read_code", "run_bash"],
           "experts/specialty/fintech-engineer.md", "sonnet", 3, &[],
           "VoltAgent", "MIT", "specialty"),
        ec("technical-writer-pro", "技术写作者", "✍️", "README·白皮书·对外文档",
           "写对外文档/README/白皮书时",
           &["技术写作", "README", "文档"],
           "写作",
           &["technical-writing", "readme", "documentation"],
           &["read_code", "run_bash"],
           "experts/specialty/technical-writer-pro.md", "sonnet", 1, &[],
           "VoltAgent", "MIT", "specialty"),

        // ── 文档/技术写作 (5) ──
        ec("docs-architect", "文档架构师", "📚", "Diátaxis·信息架构",
           "建文档体系/信息架构时",
           &["文档", "Diátaxis", "信息架构"],
           "文档",
           &["documentation", "diataxis"],
           &["read_code", "run_bash"],
           "experts/docs/docs-architect.md", "sonnet", 2, &[],
           "wshobson", "MIT", "docs"),
        ec("api-documenter", "API文档师", "📡", "OpenAPI·示例·参考",
           "写 API 文档/参考手册时",
           &["API文档", "OpenAPI", "参考"],
           "API文档",
           &["api-docs", "openapi", "reference"],
           &["read_code", "run_bash"],
           "experts/docs/api-documenter.md", "sonnet", 1, &[],
           "wshobson", "MIT", "docs"),
        ec("tutorial-engineer", "教程工程师", "📖", "循序渐进·可跑",
           "写上手教程/可跑示例时",
           &["教程", "示例", "上手"],
           "教程",
           &["tutorial", "example", "onboarding"],
           &["read_code", "run_bash"],
           "experts/docs/tutorial-engineer.md", "sonnet", 2, &[],
           "wshobson", "MIT", "docs"),
        ec("mermaid-expert", "图表专家", "📊", "流程图·时序·架构图",
           "要画流程/时序/架构图时",
           &["图表", "Mermaid", "流程图", "时序"],
           "图表",
           &["mermaid", "diagram", "flowchart"],
           &["read_code", "run_bash"],
           "experts/docs/mermaid-expert.md", "sonnet", 1, &[],
           "wshobson", "MIT", "docs"),
        ec("technical-writer", "技术写作", "✍️", "README·白皮书·对外文档",
           "写对外文档/README/白皮书时",
           &["技术写作", "README", "白皮书"],
           "写作",
           &["technical-writing", "readme"],
           &["read_code", "run_bash"],
           "experts/docs/technical-writer.md", "sonnet", 1, &[],
           "VoltAgent", "MIT", "docs"),

        // ── 产品/项目/战略 (8) ──
        ec("product-manager", "产品经理", "📦", "PRD·优先级·取舍",
           "写 PRD/排优先级/需求取舍时",
           &["产品经理", "PRD", "优先级", "需求"],
           "产品",
           &["product", "prd", "prioritization"],
           &["read_code", "run_bash"],
           "experts/product/product-manager.md", "sonnet", 2, &[],
           "MetaGPT", "MIT", "product"),
        ec("delivery-manager", "项目交付管理", "📅", "风险登记·依赖·关键路径",
           "管交付/风险/依赖/排期时",
           &["交付", "项目管理", "风险", "依赖"],
           "交付",
           &["delivery", "project-management", "risk"],
           &["read_code", "run_bash"],
           "experts/product/delivery-manager.md", "sonnet", 1, &[],
           "VoltAgent", "MIT", "product"),
        ec("scrum-master", "Scrum Master", "🏃", "迭代·阻塞清除",
           "跑迭代/清障/敏捷时",
           &["Scrum", "敏捷", "迭代"],
           "Scrum",
           &["scrum", "agile", "iteration"],
           &["read_code", "run_bash"],
           "experts/product/scrum-master.md", "sonnet", 1, &[],
           "VoltAgent", "MIT", "product"),
        ec("business-analyst", "业务分析师", "📊", "需求·流程·指标",
           "需求/流程/业务建模时",
           &["业务分析", "需求", "流程"],
           "业务",
           &["business-analysis", "requirements"],
           &["read_code", "run_bash"],
           "experts/product/business-analyst.md", "sonnet", 2, &[],
           "wshobson", "MIT", "product"),
        ec("ux-researcher", "用户研究", "👥", "访谈·JTBD·可用性",
           "用户访谈/可用性/需求挖掘时",
           &["用户研究", "访谈", "JTBD"],
           "用户研究",
           &["ux", "user-research", "jtdb"],
           &["read_code", "run_bash"],
           "experts/product/ux-researcher.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "product"),
        ec("growth-experimenter", "增长实验设计", "📈", "A/B·北极星指标·漏斗",
           "做增长/A-B 测试/漏斗时",
           &["增长", "A/B测试", "漏斗"],
           "增长",
           &["growth", "ab-test", "funnel"],
           &["read_code", "run_bash"],
           "experts/product/growth-experimenter.md", "sonnet", 2, &[],
           "补强", "北极星综合", "product"),
        ec("financial-modeler", "财务建模", "💰", "单位经济·定价·ROI",
           "算账/单位经济/ROI 测算时",
           &["财务建模", "ROI", "单位经济", "定价"],
           "财务",
           &["financial", "roi", "unit-economics"],
           &["read_code", "run_bash"],
           "experts/product/financial-modeler.md", "sonnet", 3, &[],
           "补强", "北极星综合", "product"),
        ec("pricing-strategist", "定价策略", "💵", "定价模型·弹性·打包",
           "定价/打包/商业化时",
           &["定价", "定价策略", "商业化"],
           "定价",
           &["pricing", "monetization"],
           &["read_code", "run_bash"],
           "experts/product/pricing-strategist.md", "sonnet", 2, &[],
           "NicholasSpisak", "未明示", "product"),

        // ── 研究/分析 (7) ──
        ec("deep-research", "深度研究", "🔬", "多源检索·对抗校验",
           "调研/综述/尽调/选型时",
           &["深度研究", "调研", "尽调", "选型"],
           "研究",
           &["research", "due-diligence"],
           &["read_code", "run_bash"],
           "experts/research/deep-research.md", "sonnet", 3, &[],
           "wshobson", "MIT", "research"),
        ec("competitive-analyst", "竞品分析", "🔍", "对标·差异·定位",
           "对标竞品/找差异定位时",
           &["竞品分析", "对标", "竞争"],
           "竞品",
           &["competitive-analysis", "competitor"],
           &["read_code", "run_bash"],
           "experts/research/competitive-analyst.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "research"),
        ec("market-researcher", "市场研究", "🌍", "规模·趋势·机会",
           "算市场规模/找机会时",
           &["市场研究", "市场规模", "趋势"],
           "市场",
           &["market-research", "market-size"],
           &["read_code", "run_bash"],
           "experts/research/market-researcher.md", "sonnet", 2, &[],
           "VoltAgent", "MIT", "research"),
        ec("trend-analyst", "趋势分析", "📊", "信号·拐点·预测",
           "判趋势/信号/拐点时",
           &["趋势", "拐点", "预测"],
           "趋势",
           &["trend", "analysis"],
           &["read_code", "run_bash"],
           "experts/research/trend-analyst.md", "sonnet", 2, &[],
           "contains-studio", "未明示", "research"),
        ec("scientific-researcher", "科学文献研究", "📚", "论文综述·证据分级",
           "论文综述/技术前沿/证据时",
           &["科学文献", "论文", "综述"],
           "文献",
           &["scientific", "literature", "paper"],
           &["read_code", "run_bash"],
           "experts/research/scientific-researcher.md", "sonnet", 3, &[],
           "VoltAgent", "MIT", "research"),
        ec("osint-analyst", "OSINT情报分析", "🔎", "公开情报·溯源·尽调",
           "公开情报/背调/溯源时",
           &["OSINT", "情报", "背调"],
           "情报",
           &["osint", "intelligence"],
           &["read_code", "run_bash"],
           "experts/research/osint-analyst.md", "sonnet", 2, &[],
           "补强", "北极星综合", "research"),
        ec("research-analyst", "研究分析师", "📋", "综合研究·分析报告",
           "综合研究/分析报告时",
           &["研究分析", "报告"],
           "研究",
           &["research", "analysis"],
           &["read_code", "run_bash"],
           "experts/research/research-analyst.md", "sonnet", 2, &[],
           "补强", "北极星综合", "research"),

        // ── 营销/内容 (8) ──
        ec("content-marketer", "内容营销策略", "📣", "内容矩阵·转化漏斗",
           "规划内容矩阵/转化时",
           &["内容营销", "矩阵", "转化"],
           "营销",
           &["content-marketing", "content-strategy"],
           &["read_code", "run_bash"],
           "experts/marketing/content-marketer.md", "sonnet", 1, &[],
           "wshobson", "MIT", "marketing"),
        ec("seo-specialist", "SEO专家", "🔍", "关键词·结构·收录",
           "SEO/搜索收录/排名时",
           &["SEO", "搜索", "收录"],
           "SEO",
           &["seo", "search", "ranking"],
           &["read_code", "run_bash"],
           "experts/marketing/seo-specialist.md", "sonnet", 1, &[],
           "wshobson", "MIT", "marketing"),
        ec("growth-hacker", "增长黑客", "🚀", "裂变·获客·留存",
           "裂变/获客/留存增长时",
           &["增长黑客", "获客", "留存"],
           "增长",
           &["growth-hacking", "acquisition"],
           &["read_code", "run_bash"],
           "experts/marketing/growth-hacker.md", "sonnet", 2, &[],
           "contains-studio", "未明示", "marketing"),
        ec("social-media-manager", "社媒运营", "📱", "公众号/小红书/X 运营",
           "自媒体发布/运营时",
           &["社媒", "小红书", "公众号", "运营"],
           "社媒",
           &["social-media", "operations"],
           &["read_code", "run_bash"],
           "experts/marketing/social-media-manager.md", "sonnet", 1, &[],
           "contains-studio", "未明示", "marketing"),
        ec("brand-storyteller", "叙事官/品牌故事", "🎭", "钩子·情绪曲线",
           "成品要打动人/讲故事时",
           &["品牌故事", "叙事", "钩子"],
           "品牌",
           &["brand", "storytelling"],
           &["read_code", "run_bash"],
           "experts/marketing/brand-storyteller.md", "sonnet", 3, &[],
           "contains-studio", "未明示", "marketing"),
        ec("visual-designer", "视觉设计", "🎨", "版式·视觉叙事·PPT 美学",
           "要好看/版式/视觉时",
           &["视觉设计", "PPT", "版式"],
           "视觉",
           &["visual-design", "layout"],
           &["read_code", "run_bash"],
           "experts/marketing/visual-designer.md", "sonnet", 2, &[],
           "contains-studio", "未明示", "marketing"),
        ec("pitch-coach", "路演/演讲教练", "🎤", "结构·表达·台风",
           "PPT/路演/对外汇报表达时",
           &["路演", "演讲", "表达"],
           "演讲",
           &["pitch", "presentation", "speaking"],
           &["read_code", "run_bash"],
           "experts/marketing/pitch-coach.md", "sonnet", 1, &[],
           "f/awesome-chatgpt-prompts", "MIT+CC0", "marketing"),
        ec("copywriter", "文案/口播", "✍️", "标题·口播稿·钩子",
           "写文案/口播稿/标题/幽默钩子时",
           &["文案", "口播", "标题", "钩子"],
           "文案",
           &["copywriting", "headline", "hook"],
           &["read_code", "run_bash"],
           "experts/marketing/copywriter.md", "sonnet", 1, &[],
           "f/awesome-chatgpt-prompts", "MIT+CC0", "marketing"),
    ]
}
